### ISSUE TITLE
About generating 3D ground truth for custom trajectory on the AVD dataset 

### ISSUE THREAD

**Issue by Yi-Shi94** [ai4ce/DeepMapping#6]
Hello, Thanks for the nice work. I am quite new in this field, I have run into the problem of getting 3D ground truth for custom trajectory. I can use the following function 

      def transform_to_global_AVD(pose, obs_local):  
      - transform obs local coordinate to global corrdinate frame . 
      - :param pose: <Bx3> <x,z,theta> y = 0 . 
      - :param obs_local: <BxLx3> (unorganized) or <BxHxWx3> (organized) . 
      - :return obs_global: <BxLx3> (unorganized) or <BxHxWx3> (organized) .    

on estimated pose (B*3)<x,z,theta> which was obtained by L-NET.  

However, the ground truth pose has the size of (B*6).  So I treated it as <x,y,z,dx,dy,dz> and transform it into <x,z,theta>:

`
  gt_angle_y 
  =np.arctan2(np.sqrt(gt_pose[:,3]*gt_pose[:,3]+gt_pose[:,5]*gt_pose[:,5]),gt_pose[:,4])
  gt_pose_xzth = np.vstack((gt_pose[:,0],gt_pose[:,2],gt_angle_y)).transpose()
` 

However, the result is not correct.  I also tried to use a translation matrix and three rotation matrixes along each axis. It also failed. How can I do this?

**Comment by dmax123** [comment]
Hi, 
The AVD dataset uses a robotic platform to visit a set of discrete points. In this way, the y-value remains approximately the same (distance from the robot to the ground). So the L-net does not predict it. For rotation, the AVD dataset only has one degree-of-freedom (yaw). More details about this dataset can be found on their website.

If you are going to predict 6-DOF for other dataset, you need (1) change the number of output in the L-Net to 6, and (2) write the `transform_to_global(pose, obs_local)` function

**Comment by WordBearerYI** [comment]
Hi thank you for your answer. I still have the following question:  

Based on what you said: _the y-value remains approximately the same & it only has one degree-of-freedom (yaw)._   Since the ground truth poses you got from image_struct is (16*6)<B*6> each ground truth pose was given in a Vector with the size of (6). We have x,y,z in Vector[:3], and we have a unit vector Vector[3:]. I am stuck at changing this unit vector to yaw. I don't really know what this unit vector represents. I am not able to find a document for this on the AVD dataset website. 

My motive is: I can see you have a ground truth 3d visualization in the paper. I just want to display the ground truth in eval_vis_AVD.py in the same way. Can you show me how you did it?

Really appreciate your help.
